language: ruby
rvm:
- 2.6.3
notifications:
  email: false
env:
- DB=postgresql
before_install:
- nvm install --lts
before_script:
- cp config/database.travis.yml config/database.yml
- bundle install --jobs=3 --retry=3
- yarn
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
after_failure:
- cat ./config/database.yml
- echo $RAILS_ENV
- bundle exec rake --version
cache:
- bundler
- yarn
services:
- postgresql
addons:
  postgresql: '9.4'
